Fix display, since HEAD is less than 6
This was crashing with this error:

  thread 'main' panicked at src/index_page.rs:21:89:
  byte index 6 is out of bounds of `HEAD`

It took me a while to see this HEAD is for git, not HTTP.